name: Test Backup Script

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install PostgreSQL
      run: sudo apt-get update && sudo apt-get install -y postgresql

    - name: Start PostgreSQL service
      run: sudo service postgresql start

    - name: Create PostgreSQL user and database
      run: |
        cd /tmp
        
        sudo -u postgres psql -c "CREATE DATABASE omero_database;"

    - name: Create backup directory
      run: sudo mkdir -p /tmp/OMERO/backup/database

    - name: Set permissions for backup directory
      run: sudo chown -R postgres /tmp/OMERO/backup/database

    - name: Run the backup script
      run: sudo -u postgres -c "pg_dump -Fc -f /tmp/OMERO/backup/database/omero_database.0816.pg_dump omero_database"


    - name: Verify backup
      run: ls /tmp/OMERO/backup/database/*.pg_dump
