---
- name: Deploy OMERO database script and .env file 
  hosts: all
  become: yes

  vars:
    local_scripts_dir: "{{ playbook_dir }}/../scripts"

  tasks:
    - name: Check if the cron package is installed
      package_facts:

    - name: Ensure cron is installed
      package:
        name: cron
        state: present
      when: "'cron' not in ansible_facts.packages"

    - name: Ensure cron service is running and enabled
      service:
        name: cron
        state: started
        enabled: yes

    - name: Check if the database_backup.sh cron job already exists
      stat:
        path: /etc/cron.daily/database_backup.sh
      register: cron_exists

    - name: Notify if the cron job already exists
      debug:
        msg: "The database_backup.sh cron job already exists."
      when: cron_exists.stat.exists

    - name: Copy the backup script to the host
      copy:
        src: "{{local_scripts_dir}}/database_backup.sh" 
        dest: /tmp/database_backup.sh
        mode: '0755'
      when: not cron_exists.stat.exists

    - name: Ensure the script is executable
      file:
        path: /tmp/database_backup.sh
        mode: '0755'
        state: file
      when: not cron_exists.stat.exists

    - name: Move the script to /etc/cron.daily
      command: mv /tmp/database_backup.sh /etc/cron.daily/database_backup.sh
      args:
        removes: /tmp/database_backup.sh
      when: not cron_exists.stat.exists
    
    - name: Ensure the /etc/omero directory exists
      file:
        path: /etc/omero
        state: directory
        mode: '0755'

    - name: Copy the .env file to the desired location
      copy:
        src: "{{ local_scripts_dir }}/.env" 
        dest: /etc/omero/.env         
        mode: '0600'                   
      when: not cron_exists.stat.exists

    - name: Verify the .env file is in the correct location
      stat:
        path: /etc/omero/.env
      register: env_file

    - name: Display a success message if the .env file was deployed
      debug:
        msg: ".env file successfully deployed to /etc/omero/.env"
      when: env_file.stat.exists

    - name: Display a success message if the script was deployed
      debug:
        msg: "Backup script successfully deployed to /etc/cron.daily/omero_backup.sh"
      when: not cron_exists.stat.exists and env_file.stat.exists